# Generated by Django 5.0.6 on 2024-05-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='due',
            field=models.CharField(default='12/12/24', max_length=200),
            preserve_default=False,
        ),
    ]
